"""Build TG_ListenProbe.mod from TG_Comms.sys, so the probe carries the listener helper VERBATIM.

    python make_listen_probe.py        (writes TG_ListenProbe.mod next to this script)

Why a generated copy (socket start latency item 1, 2026-09-25): TG_Comms.sys is the system
module every program depends on; a load that fails on it erases it and puts the task into
system failure state (tools/rapid_check.py header). So `tgTryOpenListener` / `tgOpenListener`
are proven on RobotWare inside this throwaway module first, against a port nothing else uses,
and only then deployed for real. Copying them by hand would prove a different text; this
script copies the two routines byte for byte and renames only the diagnostics PERS
(`nTG_ListenRetries` -> `nLpRetries`), so the probe can load beside the old AND the new
TG_Comms.sys without a name clash.

Driven by listen_probe.py. Never loaded on a production controller.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMMS = os.path.join(HERE, "..", "..", "abb", "rapid", "TG_Comms.sys")
OUT = os.path.join(HERE, "TG_ListenProbe.mod")


def routine(text, header):
    start = text.index(header)
    end_kw = "ENDFUNC" if header.lstrip().startswith(("LOCAL FUNC", "FUNC")) else "ENDPROC"
    end = text.index(end_kw, start) + len(end_kw)
    return text[start:end]


def main():
    with io.open(COMMS, "r", encoding="ascii", newline="") as fh:
        comms = fh.read().replace("\r\n", "\n")
    helpers = [routine(comms, "    LOCAL FUNC bool tgTryOpenListener(num nPort)"),
               routine(comms, "    LOCAL PROC tgOpenListener(num nPort)")]
    consts = re.findall(r"^    LOCAL CONST num TG_LISTEN_\w+:=[0-9.]+;$", comms, re.M)
    if len(consts) != 2:
        sys.exit("expected the two TG_LISTEN_ constants in TG_Comms.sys, found %d" % len(consts))
    body = "\n\n".join(h.replace("nTG_ListenRetries", "nLpRetries") for h in helpers)

    probe = """MODULE TG_ListenProbe
    ! GENERATED by make_listen_probe.py from TG_Comms.sys - do not edit;
    ! regenerate. Bench probe for the listener open with a bounded retry
    ! (socket start latency item 1, 2026-09-25): tgTryOpenListener and
    ! tgOpenListener below are TG_Comms.sys's text verbatim, with only the
    ! diagnostics PERS renamed. Own sockets, own port (nLpPort, 2002), so the
    ! HMI's connect loop on 2001 never sees it. Driven by listen_probe.py.

{consts}
    LOCAL VAR socketdev tg_server_socket;
    LOCAL VAR socketdev tg_client_socket;
    LOCAL VAR clock lpClk;

    ! Results, read by listen_probe.py over RWS.
    PERS num nLpPort:=2002;
    PERS num nLpRetries:=0;
    PERS num nLpOpenMs:=0;
    PERS num nLpErrno:=0;
    PERS num nLpLoops:=0;
    PERS num nLpMaxRetries:=0;
    PERS num nLpTotalRetries:=0;
    PERS string stLpStep:="";

{body}

    ! A: one open (timed), one accepted client, closed the handshake's way
    ! (listener first, then client - TG_HandshakeDisc).
    PROC TG_LpOpenOnce()
        stLpStep:="once: opening";
        nLpErrno:=0;
        ClkReset lpClk;
        ClkStart lpClk;
        tgOpenListener nLpPort;
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\\HighRes)*1000;
        stLpStep:="once: accepting";
        SocketAccept tg_server_socket,tg_client_socket\\Time:=30;
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        stLpStep:="once: done";
    ERROR
        nLpErrno:=ERRNO;
        stLpStep:="once: error "+NumToStr(ERRNO,0);
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC

    ! C: twenty open / accept / close rounds with NO pause - the port is
    ! re-bound right after the robot actively closed the previous
    ! connection, a tighter case than any Production Manager part sequence.
    PROC TG_LpLoop()
        stLpStep:="loop: start";
        nLpErrno:=0;
        nLpLoops:=0;
        nLpMaxRetries:=0;
        nLpTotalRetries:=0;
        FOR i FROM 1 TO 20 DO
            stLpStep:="loop "+NumToStr(i,0)+": opening";
            tgOpenListener nLpPort;
            IF nLpRetries>nLpMaxRetries nLpMaxRetries:=nLpRetries;
            nLpTotalRetries:=nLpTotalRetries+nLpRetries;
            stLpStep:="loop "+NumToStr(i,0)+": accepting";
            SocketAccept tg_server_socket,tg_client_socket\\Time:=30;
            SocketClose tg_server_socket;
            SocketClose tg_client_socket;
            Incr nLpLoops;
        ENDFOR
        stLpStep:="loop: done";
    ERROR
        nLpErrno:=ERRNO;
        stLpStep:="loop: error "+NumToStr(ERRNO,0);
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC

    ! D: the port stays busy past the budget. Expected: the warning, then
    ! the last attempt's socket error reaches THIS handler (as it would reach
    ! tgMainCycle's), recorded in nLpErrno.
    PROC TG_LpExhaust()
        stLpStep:="exhaust: opening";
        nLpErrno:=0;
        ClkReset lpClk;
        ClkStart lpClk;
        tgOpenListener nLpPort;
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\\HighRes)*1000;
        stLpStep:="exhaust: opened";
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
    ERROR
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\\HighRes)*1000;
        nLpErrno:=ERRNO;
        stLpStep:="exhaust: error reached the caller";
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC
ENDMODULE
""".format(consts="\n".join(consts), body=body)
    with io.open(OUT, "w", encoding="ascii", newline="\r\n") as fh:
        fh.write(probe)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
