MODULE TG_ListenProbe
    ! GENERATED by make_listen_probe.py from TG_Comms.sys - do not edit;
    ! regenerate. Bench probe for the listener open with a bounded retry
    ! (socket start latency item 1, 2026-09-25): tgTryOpenListener and
    ! tgOpenListener below are TG_Comms.sys's text verbatim, with only the
    ! diagnostics PERS renamed. Own sockets, own port (nLpPort, 2002), so the
    ! HMI's connect loop on 2001 never sees it. Driven by listen_probe.py.

    LOCAL CONST num TG_LISTEN_TRIES:=12;
    LOCAL CONST num TG_LISTEN_RETRY_S:=0.25;
    LOCAL VAR socketdev tg_server_socket;
    LOCAL VAR socketdev tg_client_socket;
    LOCAL VAR clock lpClk;

    ! Results, read by listen_probe.py over RWS.
    PERS num nLpPort:=2002;
    PERS num nLpRetries:=0;
    PERS num nLpOpenMs:=0;
    PERS num nLpErrno:=0;
    PERS num nLpLoops:=0;
    PERS num nLpMaxRetries:=0;
    PERS num nLpTotalRetries:=0;
    PERS string stLpStep:="";

    LOCAL FUNC bool tgTryOpenListener(num nPort)
        ! One attempt at a fresh listener on nPort. SocketClose is safe on
        ! sockets that were never opened (RoboDK driver uses the same
        ! close-before-create pattern on RW5/6). FALSE when any step failed -
        ! typically the port is not free yet - with the half-built socket
        ! closed, so the next attempt starts from nothing.
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        SocketCreate tg_server_socket;
        SocketBind tg_server_socket,stTG_ServerIP,nPort;
        SocketListen tg_server_socket;
        RETURN TRUE;
    ERROR
        SocketClose tg_server_socket;
        RETURN FALSE;
    ENDFUNC

    LOCAL PROC tgOpenListener(num nPort)
        ! Open the listener on nPort at once; retry only a port that is not
        ! free yet (socket start latency item 1). Replaces a blind 2 s wait
        ! at the start of every part: the previous part already ended with
        ! TG_SocketDisc's wait, and an aborted part (tgCycleAbort, no wait)
        ! is followed by Production Manager's abort hooks and the next index
        ! before any port is bound again - so the port is normally free and
        ! this costs nothing. Out of tries: one last attempt WITHOUT the
        ! catch, so the socket error reaches the caller exactly as it did
        ! before the retry existed (tgMainCycle abandons the cycle).
        ! The ERROR handler below is what carries it there: an error raised
        ! in a routine WITHOUT a handler goes to the system error handler and
        ! stops the task (40228, VC-measured), it does not reach the caller.
        VAR num nTry:=0;
        WHILE NOT tgTryOpenListener(nPort) DO
            Incr nTry;
            IF nTry>=TG_LISTEN_TRIES THEN
                nLpRetries:=nTry;
                ErrWrite \W,"TG: listener port busy","Port "+NumToStr(nPort,0)+" still busy after "+NumToStr(nTry,0)+" attempts - last attempt.";
                SocketClose tg_server_socket;
                SocketClose tg_client_socket;
                SocketCreate tg_server_socket;
                SocketBind tg_server_socket,stTG_ServerIP,nPort;
                SocketListen tg_server_socket;
                RETURN;
            ENDIF
            IF nTry=1 TPWrite "TG: port "+NumToStr(nPort,0)+" busy - retrying";
            WaitTime TG_LISTEN_RETRY_S;
        ENDWHILE
        nLpRetries:=nTry;
        IF nTry>0 ErrWrite \I,"TG: listener port was busy","Port "+NumToStr(nPort,0)+" opened after "+NumToStr(nTry,0)+" retries.";
    ERROR
        RAISE;
    ENDPROC

    ! A: one open (timed), one accepted client, closed the handshake's way
    ! (listener first, then client - TG_HandshakeDisc).
    PROC TG_LpOpenOnce()
        stLpStep:="once: opening";
        nLpErrno:=0;
        ClkReset lpClk;
        ClkStart lpClk;
        tgOpenListener nLpPort;
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\HighRes)*1000;
        stLpStep:="once: accepting";
        SocketAccept tg_server_socket,tg_client_socket\Time:=30;
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        stLpStep:="once: done";
    ERROR
        nLpErrno:=ERRNO;
        stLpStep:="once: error "+NumToStr(ERRNO,0);
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC

    ! C: twenty open / accept / close rounds with NO pause - the port is
    ! re-bound right after the robot actively closed the previous
    ! connection, a tighter case than any Production Manager part sequence.
    PROC TG_LpLoop()
        stLpStep:="loop: start";
        nLpErrno:=0;
        nLpLoops:=0;
        nLpMaxRetries:=0;
        nLpTotalRetries:=0;
        FOR i FROM 1 TO 20 DO
            stLpStep:="loop "+NumToStr(i,0)+": opening";
            tgOpenListener nLpPort;
            IF nLpRetries>nLpMaxRetries nLpMaxRetries:=nLpRetries;
            nLpTotalRetries:=nLpTotalRetries+nLpRetries;
            stLpStep:="loop "+NumToStr(i,0)+": accepting";
            SocketAccept tg_server_socket,tg_client_socket\Time:=30;
            SocketClose tg_server_socket;
            SocketClose tg_client_socket;
            Incr nLpLoops;
        ENDFOR
        stLpStep:="loop: done";
    ERROR
        nLpErrno:=ERRNO;
        stLpStep:="loop: error "+NumToStr(ERRNO,0);
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC

    ! D: the port stays busy past the budget. Expected: the warning, then
    ! the last attempt's socket error reaches THIS handler (as it would reach
    ! tgMainCycle's), recorded in nLpErrno.
    PROC TG_LpExhaust()
        stLpStep:="exhaust: opening";
        nLpErrno:=0;
        ClkReset lpClk;
        ClkStart lpClk;
        tgOpenListener nLpPort;
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\HighRes)*1000;
        stLpStep:="exhaust: opened";
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
    ERROR
        ClkStop lpClk;
        nLpOpenMs:=ClkRead(lpClk\HighRes)*1000;
        nLpErrno:=ERRNO;
        stLpStep:="exhaust: error reached the caller";
        SocketClose tg_server_socket;
        SocketClose tg_client_socket;
        RETURN;
    ENDPROC
ENDMODULE
