/PROG  TD05tRJYQd
/ATTR
OWNER		= MNEDITOR;
COMMENT		= "Generated by TetraGen Robotics Inc.";
PROG_SIZE	= 0;
CREATE		= DATE 26-02-25  TIME 12:00:00;
MODIFIED	= DATE 26-02-25  TIME 12:00:00;
FILE_NAME	= ;
VERSION		= 0;
LINE_COUNT	= 413;
MEMORY_SIZE	= 0;
PROTECT		= READ_WRITE;
TCD:  STACK_SIZE	= 0,
      TASK_PRIORITY	= 50,
      TIME_SLICE		= 0,
      BUSY_LAMP_OFF	= 0,
      ABORT_REQUEST	= 0,
      PAUSE_REQUEST	= 0;
DEFAULT_GROUP	= 1,*,*,*,*;
CONTROL_CODE	= 00000000 00000000;
/MN
   1:  UFRAME[9]=PR[9] ;
   2:  UFRAME_NUM=9 ;
   3:  UTOOL[8]=PR[8] ;
   4:  UTOOL_NUM=8 ;
   5:  CALL SHome ;
   6:  CALL P_0 ;
   7:  CALL SET_PASS_SR('TD05tRJYQd') ;
   8:  CALL SET_ROB_S_SR('Ok') ;
   9:  CALL R_P_C ;
  10:  IF (R[200] = 0) THEN ;
  11:  END ;
  12:  ENDIF ;
  13:  CALL DRY_RUN_OFF ;
  14:  IF (R[199] = 1) THEN ;
  15:  CALL DRY_RUN_ON ;
  16:  ENDIF ;
  17:  PAYLOAD[1] ;
  18:  !-- CALL CAM_PREP ;
  19:  CALL WELD_PREP ;
  20:  ! Transition ;
  21:  UFRAME[6]=PR[6] ;
  22:  UFRAME_NUM=6 ;
  23:  J P[1] 100% CNT100 ;
  24:  CALL RAIL_0 ;
  25:  CALL P_M45 ;
  26:  J P[2] 100% CNT100 ;
  27:  ! Capture set Captures (-45.0°) ;
  28:  UFRAME[5]=PR[5] ;
  29:  UFRAME_NUM=5 ;
  30:  UTOOL[2]=PR[2] ;
  31:  UTOOL_NUM=2 ;
  32:  J P[3] 80% CNT100 ;
  33:  J P[4] 80% CNT100 ;
  34:  J P[5] 80% CNT100 ;
  35:  CALL SET_SUB_ROUTINE_SR('C1PGlobal_m45_3') ;
  36:  CALL R_C_F ;
  37:  IF (R[197] = 1) THEN ;
  38:  CALL CAM_OPEN ;
  39:  UFRAME[5]=PR[5] ;
  40:  J P[6] 80% FINE ;
  41:  WAIT 0.20(sec) ;
  42:  CALL R_C ;
  43:  IF R[196] = 0, JMP LBL[101] ;
  44:  ENDIF ;
  45:  J P[7] 80% CNT100 ;
  46:  J P[8] 80% CNT100 ;
  47:  CALL SET_SUB_ROUTINE_SR('C2PGlobal_m45_3') ;
  48:  CALL R_C_F ;
  49:  IF (R[197] = 1) THEN ;
  50:  CALL CAM_OPEN ;
  51:  UFRAME[5]=PR[5] ;
  52:  J P[9] 80% FINE ;
  53:  WAIT 0.20(sec) ;
  54:  CALL R_C ;
  55:  IF R[196] = 0, JMP LBL[101] ;
  56:  ENDIF ;
  57:  J P[10] 80% CNT100 ;
  58:  J P[11] 80% CNT100 ;
  59:  J P[12] 80% CNT100 ;
  60:  ! End of capture set ;
  61:  CALL R_G_C_D ;
  62:  CALL CAM_CLOSE ;
  63:  CALL WELD_PREP ;
  64:  ! Transition ;
  65:  UFRAME[6]=PR[6] ;
  66:  UFRAME_NUM=6 ;
  67:  UTOOL[8]=PR[8] ;
  68:  UTOOL_NUM=8 ;
  69:  J P[13] 100% CNT100 ;
  70:  J P[14] 100% CNT100 ;
  71:  J P[15] 100% CNT100 ;
  72:  J P[16] 100% CNT100 ;
  73:  J P[17] 100% CNT100 ;
  74:  J P[18] 100% CNT100 ;
  75:  J P[19] 100% CNT100 ;
  76:  ! TouchSense for Weld2 ;
  77:  CALL SET_SUB_ROUTINE_SR('TSPWeld2_full') ;
  78:  CALL R_W_F ;
  79:  CALL R_TS_D ;
  80:  CALL CAM_CLOSE ;
  81:  IF (R[195:doTouchSense]=1) THEN ;
  82:  CALL R_TS_F ;
  83:  CALL TEACHMODE_ON ;
  84:  Search Start [2] PR[10] ;
  85:  UFRAME[6]=PR[6] ;
  86:  J P[20] 100% CNT100 ;
  87:  J P[21] 100% CNT100 ;
  88:  J P[22] 100% CNT100 ;
  89:  J P[23] 100% CNT100 ;
  90:  J P[24] 100% CNT100 ;
  91:  J P[25] 100% CNT100 ;
  92:  J P[26] 100% CNT100 ;
  93:  J P[27] 100% CNT100 ;
  94:  J P[28] 100% CNT100 ;
  95:  J P[29] 100% CNT100 ;
  96:  J P[30] 100% CNT100 ;
  97:  J P[31] 100% CNT100 ;
  98:  J P[32] 100% CNT100 ;
  99:  J P[33] 100% CNT100 ;
 100:  J P[34] 100% CNT100 ;
 101:  J P[35] 100% CNT100 ;
 102:  J P[36] 100% CNT100 ;
 103:  J P[37] 100% CNT100 ;
 104:  J P[38] 100% CNT100 ;
 105:  J P[39] 100% CNT100 ;
 106:  J P[40] 100% CNT100 ;
 107:  J P[41] 100% CNT100 ;
 108:  J P[42] 100% CNT100 ;
 109:  J P[43] 100% CNT100 ;
 110:  J P[44] 100% CNT100 ;
 111:  J P[45] 100% CNT100 ;
 112:  J P[46] 100% CNT100 ;
 113:  J P[47] 100% CNT100 ;
 114:  J P[48] 100% CNT100 ;
 115:  J P[49] 100% CNT100 ;
 116:  J P[50] 100% CNT100 ;
 117:  J P[51] 100% CNT100 ;
 118:  L P[52] 775mm/sec FINE ;
 119:  L P[53] 775mm/sec FINE Search[+X] ;
 120:  CALL R_TS_P ;
 121:  WAIT 0.50(sec) ;
 122:  L P[54] 775mm/sec FINE ;
 123:  UFRAME[6]=PR[6] ;
 124:  J P[55] 100% CNT100 ;
 125:  J P[56] 100% CNT100 ;
 126:  J P[57] 100% CNT100 ;
 127:  J P[58] 100% CNT100 ;
 128:  J P[59] 100% CNT100 ;
 129:  J P[60] 100% CNT100 ;
 130:  J P[61] 100% CNT100 ;
 131:  J P[62] 100% CNT100 ;
 132:  J P[63] 100% CNT100 ;
 133:  J P[64] 100% CNT100 ;
 134:  J P[65] 100% CNT100 ;
 135:  J P[66] 100% CNT100 ;
 136:  J P[67] 100% CNT100 ;
 137:  J P[68] 100% CNT100 ;
 138:  J P[69] 100% CNT100 ;
 139:  J P[70] 100% CNT100 ;
 140:  J P[71] 100% CNT100 ;
 141:  J P[72] 100% CNT100 ;
 142:  J P[73] 100% CNT100 ;
 143:  J P[74] 100% CNT100 ;
 144:  J P[75] 100% CNT100 ;
 145:  J P[76] 100% CNT100 ;
 146:  J P[77] 100% CNT100 ;
 147:  J P[78] 100% CNT100 ;
 148:  J P[79] 100% CNT100 ;
 149:  J P[80] 100% CNT100 ;
 150:  J P[81] 100% CNT100 ;
 151:  J P[82] 100% CNT100 ;
 152:  J P[83] 100% CNT100 ;
 153:  J P[84] 100% CNT100 ;
 154:  J P[85] 100% CNT100 ;
 155:  J P[86] 100% CNT100 ;
 156:  L P[87] 775mm/sec FINE ;
 157:  L P[88] 775mm/sec FINE Search[-Z] ;
 158:  CALL R_TS_P ;
 159:  WAIT 0.50(sec) ;
 160:  L P[89] 775mm/sec FINE ;
 161:  UFRAME[6]=PR[6] ;
 162:  J P[90] 100% CNT100 ;
 163:  J P[91] 100% CNT100 ;
 164:  J P[92] 100% CNT100 ;
 165:  J P[93] 100% CNT100 ;
 166:  J P[94] 100% CNT100 ;
 167:  J P[95] 100% CNT100 ;
 168:  J P[96] 100% CNT100 ;
 169:  J P[97] 100% CNT100 ;
 170:  J P[98] 100% CNT100 ;
 171:  J P[99] 100% CNT100 ;
 172:  J P[100] 100% CNT100 ;
 173:  J P[101] 100% CNT100 ;
 174:  J P[102] 100% CNT100 ;
 175:  J P[103] 100% CNT100 ;
 176:  J P[104] 100% CNT100 ;
 177:  J P[105] 100% CNT100 ;
 178:  J P[106] 100% CNT100 ;
 179:  J P[107] 100% CNT100 ;
 180:  J P[108] 100% CNT100 ;
 181:  J P[109] 100% CNT100 ;
 182:  J P[110] 100% CNT100 ;
 183:  J P[111] 100% CNT100 ;
 184:  J P[112] 100% CNT100 ;
 185:  J P[113] 100% CNT100 ;
 186:  J P[114] 100% CNT100 ;
 187:  J P[115] 100% CNT100 ;
 188:  J P[116] 100% CNT100 ;
 189:  J P[117] 100% CNT100 ;
 190:  J P[118] 100% CNT100 ;
 191:  J P[119] 100% CNT100 ;
 192:  J P[120] 100% CNT100 ;
 193:  Search End ;
 194:  CALL R_TS_END ;
 195:  ENDIF ;
 196:  ! End of TouchSense for Weld2 ;
 197:  ! Start of Weld2 ;
 198:  UFRAME[6]=PR[6] ;
 199:  CALL SET_SUB_ROUTINE_SR('PWeld2') ;
 200:  CALL R_W_F ;
 201:  CALL CAM_CLOSE ;
 202:  UFRAME[6]=PR[6] ;
 203:  IF R[198] = 2, JMP LBL[101] ;
 204:  IF (R[198] = 1) THEN ;
 205:  J P[121] 100% CNT100 ;
 206:  L P[122] 775mm/sec CNT100 ;
 207:  L P[123] 775mm/sec CNT100 ;
 208:  !--TPNUm:2 ;
 209:  CALL R_W_P ;
 210:  IF (R[170]=0) THEN ;
 211:  WELD START[1,1] ;
 212:  ENDIF ;
 213:  IF (R[170]=1) THEN ;
 214:  WELD START[R[171],20] ;
 215:  ENDIF ;
 216:  L P[124] R[175]inch/min FINE ;
 217:  IF (R[170]=0) THEN ;
 218:  WELD END[1,1] ;
 219:  ENDIF ;
 220:  IF (R[170]=1) THEN ;
 221:  WELD END[R[171],20] ;
 222:  ENDIF ;
 223:  CALL R_W_S ;
 224:  L P[125] 775mm/sec FINE ;
 225:  ENDIF ;
 226:  ! End of Weld2 ;
 227:  ! Transition ;
 228:  J P[126] 100% CNT100 ;
 229:  J P[127] 100% CNT100 ;
 230:  J P[128] 100% CNT100 ;
 231:  J P[129] 100% CNT100 ;
 232:  J P[130] 100% CNT100 ;
 233:  J P[131] 100% CNT100 ;
 234:  J P[132] 100% CNT100 ;
 235:  J P[133] 100% CNT100 ;
 236:  J P[134] 100% CNT100 ;
 237:  J P[135] 100% CNT100 ;
 238:  J P[136] 100% CNT100 ;
 239:  J P[137] 100% CNT100 ;
 240:  J P[138] 100% CNT100 ;
 241:  J P[139] 100% CNT100 ;
 242:  J P[140] 100% CNT100 ;
 243:  J P[141] 100% CNT100 ;
 244:  J P[142] 100% CNT100 ;
 245:  ! TouchSense for Weld3 ;
 246:  CALL SET_SUB_ROUTINE_SR('TSPWeld3_full') ;
 247:  CALL R_W_F ;
 248:  CALL R_TS_D ;
 249:  CALL CAM_CLOSE ;
 250:  IF (R[195:doTouchSense]=1) THEN ;
 251:  CALL R_TS_F ;
 252:  CALL TEACHMODE_ON ;
 253:  Search Start [2] PR[10] ;
 254:  UFRAME[6]=PR[6] ;
 255:  J P[143] 100% CNT100 ;
 256:  J P[144] 100% CNT100 ;
 257:  J P[145] 100% CNT100 ;
 258:  J P[146] 100% CNT100 ;
 259:  J P[147] 100% CNT100 ;
 260:  J P[148] 100% CNT100 ;
 261:  J P[149] 100% CNT100 ;
 262:  J P[150] 100% CNT100 ;
 263:  J P[151] 100% CNT100 ;
 264:  J P[152] 100% CNT100 ;
 265:  J P[153] 100% CNT100 ;
 266:  J P[154] 100% CNT100 ;
 267:  J P[155] 100% CNT100 ;
 268:  J P[156] 100% CNT100 ;
 269:  J P[157] 100% CNT100 ;
 270:  J P[158] 100% CNT100 ;
 271:  J P[159] 100% CNT100 ;
 272:  J P[160] 100% CNT100 ;
 273:  J P[161] 100% CNT100 ;
 274:  J P[162] 100% CNT100 ;
 275:  J P[163] 100% CNT100 ;
 276:  J P[164] 100% CNT100 ;
 277:  J P[165] 100% CNT100 ;
 278:  J P[166] 100% CNT100 ;
 279:  J P[167] 100% CNT100 ;
 280:  J P[168] 100% CNT100 ;
 281:  J P[169] 100% CNT100 ;
 282:  J P[170] 100% CNT100 ;
 283:  J P[171] 100% CNT100 ;
 284:  J P[172] 100% CNT100 ;
 285:  J P[173] 100% CNT100 ;
 286:  J P[174] 100% CNT100 ;
 287:  L P[175] 775mm/sec FINE ;
 288:  L P[176] 775mm/sec FINE Search[+X] ;
 289:  CALL R_TS_P ;
 290:  WAIT 0.50(sec) ;
 291:  L P[177] 775mm/sec FINE ;
 292:  UFRAME[6]=PR[6] ;
 293:  J P[178] 100% CNT100 ;
 294:  J P[179] 100% CNT100 ;
 295:  J P[180] 100% CNT100 ;
 296:  J P[181] 100% CNT100 ;
 297:  J P[182] 100% CNT100 ;
 298:  J P[183] 100% CNT100 ;
 299:  J P[184] 100% CNT100 ;
 300:  J P[185] 100% CNT100 ;
 301:  J P[186] 100% CNT100 ;
 302:  J P[187] 100% CNT100 ;
 303:  J P[188] 100% CNT100 ;
 304:  J P[189] 100% CNT100 ;
 305:  J P[190] 100% CNT100 ;
 306:  J P[191] 100% CNT100 ;
 307:  J P[192] 100% CNT100 ;
 308:  J P[193] 100% CNT100 ;
 309:  J P[194] 100% CNT100 ;
 310:  J P[195] 100% CNT100 ;
 311:  J P[196] 100% CNT100 ;
 312:  J P[197] 100% CNT100 ;
 313:  J P[198] 100% CNT100 ;
 314:  J P[199] 100% CNT100 ;
 315:  J P[200] 100% CNT100 ;
 316:  J P[201] 100% CNT100 ;
 317:  J P[202] 100% CNT100 ;
 318:  J P[203] 100% CNT100 ;
 319:  J P[204] 100% CNT100 ;
 320:  J P[205] 100% CNT100 ;
 321:  J P[206] 100% CNT100 ;
 322:  J P[207] 100% CNT100 ;
 323:  J P[208] 100% CNT100 ;
 324:  J P[209] 100% CNT100 ;
 325:  L P[210] 775mm/sec FINE ;
 326:  L P[211] 775mm/sec FINE Search[-Z] ;
 327:  CALL R_TS_P ;
 328:  WAIT 0.50(sec) ;
 329:  L P[212] 775mm/sec FINE ;
 330:  UFRAME[6]=PR[6] ;
 331:  J P[213] 100% CNT100 ;
 332:  J P[214] 100% CNT100 ;
 333:  J P[215] 100% CNT100 ;
 334:  J P[216] 100% CNT100 ;
 335:  J P[217] 100% CNT100 ;
 336:  J P[218] 100% CNT100 ;
 337:  J P[219] 100% CNT100 ;
 338:  J P[220] 100% CNT100 ;
 339:  J P[221] 100% CNT100 ;
 340:  J P[222] 100% CNT100 ;
 341:  J P[223] 100% CNT100 ;
 342:  J P[224] 100% CNT100 ;
 343:  J P[225] 100% CNT100 ;
 344:  J P[226] 100% CNT100 ;
 345:  J P[227] 100% CNT100 ;
 346:  J P[228] 100% CNT100 ;
 347:  J P[229] 100% CNT100 ;
 348:  J P[230] 100% CNT100 ;
 349:  J P[231] 100% CNT100 ;
 350:  J P[232] 100% CNT100 ;
 351:  J P[233] 100% CNT100 ;
 352:  J P[234] 100% CNT100 ;
 353:  J P[235] 100% CNT100 ;
 354:  J P[236] 100% CNT100 ;
 355:  J P[237] 100% CNT100 ;
 356:  J P[238] 100% CNT100 ;
 357:  J P[239] 100% CNT100 ;
 358:  J P[240] 100% CNT100 ;
 359:  J P[241] 100% CNT100 ;
 360:  J P[242] 100% CNT100 ;
 361:  J P[243] 100% CNT100 ;
 362:  Search End ;
 363:  CALL R_TS_END ;
 364:  ENDIF ;
 365:  ! End of TouchSense for Weld3 ;
 366:  ! Start of Weld3 ;
 367:  UFRAME[6]=PR[6] ;
 368:  CALL SET_SUB_ROUTINE_SR('PWeld3') ;
 369:  CALL R_W_F ;
 370:  CALL CAM_CLOSE ;
 371:  UFRAME[6]=PR[6] ;
 372:  IF R[198] = 2, JMP LBL[101] ;
 373:  IF (R[198] = 1) THEN ;
 374:  J P[244] 100% CNT100 ;
 375:  L P[245] 775mm/sec CNT100 ;
 376:  L P[246] 775mm/sec CNT100 ;
 377:  !--TPNUm:2 ;
 378:  CALL R_W_P ;
 379:  IF (R[170]=0) THEN ;
 380:  WELD START[1,1] ;
 381:  ENDIF ;
 382:  IF (R[170]=1) THEN ;
 383:  WELD START[R[171],20] ;
 384:  ENDIF ;
 385:  L P[247] R[175]inch/min FINE ;
 386:  IF (R[170]=0) THEN ;
 387:  WELD END[1,1] ;
 388:  ENDIF ;
 389:  IF (R[170]=1) THEN ;
 390:  WELD END[R[171],20] ;
 391:  ENDIF ;
 392:  CALL R_W_S ;
 393:  L P[248] 775mm/sec FINE ;
 394:  ENDIF ;
 395:  ! End of Weld3 ;
 396:  ! Transition ;
 397:  J P[249] 100% CNT100 ;
 398:  J P[250] 100% CNT100 ;
 399:  J P[251] 100% CNT100 ;
 400:  J P[252] 100% CNT100 ;
 401:  J P[253] 100% CNT100 ;
 402:  J P[254] 100% CNT100 ;
 403:  CALL RAIL_0 ;
 404:  CALL P_0 ;
 405:  J P[255] 100% CNT100 ;
 406:  ! Move to rest home ;
 407:  UFRAME[9]=PR[9] ;
 408:  UFRAME_NUM=9 ;
 409:  CALL CAM_CLOSE ;
 410:  J P[256] 80% CNT100 ;
 411:  CALL P_0 ;
 412:  LBL[101] ;
 413:  CALL R_E ;
/POS
P[1]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[2]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[3]{
   GP1:
    UF : 5, UT : 2,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[4]{
   GP1:
    UF : 5, UT : 2,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[5]{
   GP1:
    UF : 5, UT : 2,
    J1=   18.389 deg, J2=   47.403 deg, J3=  -51.435 deg,
    J4=  -89.290 deg, J5=   91.920 deg, J6=  -69.896 deg
};
P[6]{
   GP1:
    UF : 5, UT : 2,
    J1=   18.389 deg, J2=   47.403 deg, J3=  -51.435 deg,
    J4=  -89.290 deg, J5=   91.920 deg, J6=  -69.896 deg
};
P[7]{
   GP1:
    UF : 5, UT : 2,
    J1=   18.389 deg, J2=   47.403 deg, J3=  -51.435 deg,
    J4=  -89.290 deg, J5=   91.920 deg, J6=  -69.896 deg
};
P[8]{
   GP1:
    UF : 5, UT : 2,
    J1=   -7.160 deg, J2=   47.149 deg, J3=  -50.237 deg,
    J4=  -89.663 deg, J5=   87.137 deg, J6=  -69.921 deg
};
P[9]{
   GP1:
    UF : 5, UT : 2,
    J1=   -7.160 deg, J2=   47.149 deg, J3=  -50.237 deg,
    J4=  -89.663 deg, J5=   87.137 deg, J6=  -69.921 deg
};
P[10]{
   GP1:
    UF : 5, UT : 2,
    J1=   -7.160 deg, J2=   47.149 deg, J3=  -50.237 deg,
    J4=  -89.663 deg, J5=   87.137 deg, J6=  -69.921 deg
};
P[11]{
   GP1:
    UF : 5, UT : 2,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[12]{
   GP1:
    UF : 5, UT : 2,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[13]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[14]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.569 deg, J2=  -12.665 deg, J3=    7.257 deg,
    J4=   13.083 deg, J5=  -35.833 deg, J6=  -11.128 deg
};
P[15]{
   GP1:
    UF : 6, UT : 8,
    J1=   10.875 deg, J2=   -0.754 deg, J3=  -14.069 deg,
    J4=   40.741 deg, J5=  -15.464 deg, J6=  -36.002 deg
};
P[16]{
   GP1:
    UF : 6, UT : 8,
    J1=   16.050 deg, J2=   13.679 deg, J3=  -38.609 deg,
    J4=   68.803 deg, J5=    4.027 deg, J6=  -60.856 deg
};
P[17]{
   GP1:
    UF : 6, UT : 8,
    J1=   15.633 deg, J2=   18.400 deg, J3=  -46.679 deg,
    J4=   77.186 deg, J5=    8.934 deg, J6=  -67.769 deg
};
P[18]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.137 deg, J2=   21.342 deg, J3=  -50.711 deg,
    J4=   82.107 deg, J5=   10.927 deg, J6=  -71.576 deg
};
P[19]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.870 deg, J2=   21.144 deg, J3=  -49.851 deg,
    J4=   82.061 deg, J5=   10.846 deg, J6=  -71.563 deg
};
P[20]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.870 deg, J2=   21.144 deg, J3=  -49.851 deg,
    J4=   82.061 deg, J5=   10.846 deg, J6=  -71.563 deg
};
P[21]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.870 deg, J2=   21.144 deg, J3=  -49.851 deg,
    J4=   82.061 deg, J5=   10.846 deg, J6=  -71.563 deg
};
P[22]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.372 deg, J2=   18.961 deg, J3=  -48.722 deg,
    J4=   83.012 deg, J5=   11.841 deg, J6=  -72.790 deg
};
P[23]{
   GP1:
    UF : 6, UT : 8,
    J1=   11.674 deg, J2=   16.918 deg, J3=  -47.903 deg,
    J4=   82.865 deg, J5=   12.946 deg, J6=  -72.859 deg
};
P[24]{
   GP1:
    UF : 6, UT : 8,
    J1=   10.959 deg, J2=   14.915 deg, J3=  -47.135 deg,
    J4=   82.656 deg, J5=   14.028 deg, J6=  -72.882 deg
};
P[25]{
   GP1:
    UF : 6, UT : 8,
    J1=   10.221 deg, J2=   12.972 deg, J3=  -46.432 deg,
    J4=   82.362 deg, J5=   15.072 deg, J6=  -72.838 deg
};
P[26]{
   GP1:
    UF : 6, UT : 8,
    J1=    9.463 deg, J2=   11.120 deg, J3=  -45.802 deg,
    J4=   81.960 deg, J5=   16.069 deg, J6=  -72.701 deg
};
P[27]{
   GP1:
    UF : 6, UT : 8,
    J1=    8.703 deg, J2=    9.392 deg, J3=  -45.255 deg,
    J4=   81.436 deg, J5=   17.015 deg, J6=  -72.443 deg
};
P[28]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.952 deg, J2=    7.809 deg, J3=  -44.793 deg,
    J4=   80.791 deg, J5=   17.904 deg, J6=  -72.050 deg
};
P[29]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.230 deg, J2=    6.395 deg, J3=  -44.421 deg,
    J4=   80.016 deg, J5=   18.723 deg, J6=  -71.519 deg
};
P[30]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.544 deg, J2=    5.177 deg, J3=  -44.155 deg,
    J4=   79.113 deg, J5=   19.461 deg, J6=  -70.842 deg
};
P[31]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.899 deg, J2=    4.174 deg, J3=  -44.006 deg,
    J4=   78.088 deg, J5=   20.115 deg, J6=  -70.023 deg
};
P[32]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.299 deg, J2=    3.406 deg, J3=  -43.983 deg,
    J4=   76.943 deg, J5=   20.680 deg, J6=  -69.061 deg
};
P[33]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.758 deg, J2=    2.885 deg, J3=  -44.082 deg,
    J4=   75.687 deg, J5=   21.147 deg, J6=  -67.953 deg
};
P[34]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.289 deg, J2=    2.609 deg, J3=  -44.290 deg,
    J4=   74.337 deg, J5=   21.513 deg, J6=  -66.704 deg
};
P[35]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.900 deg, J2=    2.576 deg, J3=  -44.587 deg,
    J4=   72.904 deg, J5=   21.778 deg, J6=  -65.331 deg
};
P[36]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.599 deg, J2=    2.788 deg, J3=  -44.972 deg,
    J4=   71.402 deg, J5=   21.941 deg, J6=  -63.852 deg
};
P[37]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.388 deg, J2=    3.243 deg, J3=  -45.436 deg,
    J4=   69.863 deg, J5=   21.997 deg, J6=  -62.280 deg
};
P[38]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.270 deg, J2=    3.940 deg, J3=  -45.979 deg,
    J4=   68.311 deg, J5=   21.944 deg, J6=  -60.634 deg
};
P[39]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.246 deg, J2=    4.866 deg, J3=  -46.599 deg,
    J4=   66.771 deg, J5=   21.780 deg, J6=  -58.931 deg
};
P[40]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.305 deg, J2=    6.012 deg, J3=  -47.297 deg,
    J4=   65.255 deg, J5=   21.510 deg, J6=  -57.188 deg
};
P[41]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.445 deg, J2=    7.360 deg, J3=  -48.074 deg,
    J4=   63.777 deg, J5=   21.141 deg, J6=  -55.416 deg
};
P[42]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.667 deg, J2=    8.889 deg, J3=  -48.933 deg,
    J4=   62.339 deg, J5=   20.679 deg, J6=  -53.632 deg
};
P[43]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.968 deg, J2=   10.579 deg, J3=  -49.878 deg,
    J4=   60.945 deg, J5=   20.126 deg, J6=  -51.853 deg
};
P[44]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.342 deg, J2=   12.398 deg, J3=  -50.894 deg,
    J4=   59.596 deg, J5=   19.491 deg, J6=  -50.083 deg
};
P[45]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.784 deg, J2=   14.314 deg, J3=  -51.962 deg,
    J4=   58.285 deg, J5=   18.784 deg, J6=  -48.331 deg
};
P[46]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.275 deg, J2=   16.292 deg, J3=  -53.056 deg,
    J4=   57.001 deg, J5=   18.009 deg, J6=  -46.594 deg
};
P[47]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.806 deg, J2=   18.302 deg, J3=  -54.153 deg,
    J4=   55.745 deg, J5=   17.175 deg, J6=  -44.876 deg
};
P[48]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.366 deg, J2=   20.330 deg, J3=  -55.259 deg,
    J4=   54.518 deg, J5=   16.287 deg, J6=  -43.181 deg
};
P[49]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.716 deg, J2=   24.303 deg, J3=  -57.212 deg,
    J4=   53.191 deg, J5=   14.271 deg, J6=  -40.973 deg
};
P[50]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.716 deg, J2=   24.303 deg, J3=  -57.212 deg,
    J4=   53.191 deg, J5=   14.271 deg, J6=  -40.973 deg
};
P[51]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.716 deg, J2=   24.303 deg, J3=  -57.212 deg,
    J4=   53.191 deg, J5=   14.271 deg, J6=  -40.973 deg
};
P[52]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -129.068  mm,    Z =   28.281  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[53]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -129.068  mm,    Z =   28.281  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[54]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -129.068  mm,    Z =   28.281  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[55]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.716 deg, J2=   24.303 deg, J3=  -57.212 deg,
    J4=   53.191 deg, J5=   14.271 deg, J6=  -40.973 deg
};
P[56]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.716 deg, J2=   24.303 deg, J3=  -57.212 deg,
    J4=   53.191 deg, J5=   14.271 deg, J6=  -40.973 deg
};
P[57]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.628 deg, J2=   23.974 deg, J3=  -57.031 deg,
    J4=   53.296 deg, J5=   14.395 deg, J6=  -41.169 deg
};
P[58]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.473 deg, J2=   23.270 deg, J3=  -56.569 deg,
    J4=   53.585 deg, J5=   14.701 deg, J6=  -41.546 deg
};
P[59]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.139 deg, J2=   22.186 deg, J3=  -55.876 deg,
    J4=   53.984 deg, J5=   15.184 deg, J6=  -42.047 deg
};
P[60]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.677 deg, J2=   20.709 deg, J3=  -54.994 deg,
    J4=   54.137 deg, J5=   15.830 deg, J6=  -42.577 deg
};
P[61]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.070 deg, J2=   18.892 deg, J3=  -53.998 deg,
    J4=   54.275 deg, J5=   16.611 deg, J6=  -43.090 deg
};
P[62]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.361 deg, J2=   16.840 deg, J3=  -52.910 deg,
    J4=   54.334 deg, J5=   17.475 deg, J6=  -43.574 deg
};
P[63]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.585 deg, J2=   14.639 deg, J3=  -51.734 deg,
    J4=   54.262 deg, J5=   18.364 deg, J6=  -44.011 deg
};
P[64]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.804 deg, J2=   12.428 deg, J3=  -50.490 deg,
    J4=   54.152 deg, J5=   19.239 deg, J6=  -44.413 deg
};
P[65]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.070 deg, J2=   10.376 deg, J3=  -49.331 deg,
    J4=   54.071 deg, J5=   20.043 deg, J6=  -44.796 deg
};
P[66]{
   GP1:
    UF : 6, UT : 8,
    J1=    2.437 deg, J2=    8.608 deg, J3=  -48.303 deg,
    J4=   54.087 deg, J5=   20.718 deg, J6=  -45.188 deg
};
P[67]{
   GP1:
    UF : 6, UT : 8,
    J1=    1.961 deg, J2=    7.205 deg, J3=  -47.476 deg,
    J4=   54.180 deg, J5=   21.253 deg, J6=  -45.574 deg
};
P[68]{
   GP1:
    UF : 6, UT : 8,
    J1=    1.674 deg, J2=    6.209 deg, J3=  -46.867 deg,
    J4=   54.376 deg, J5=   21.633 deg, J6=  -45.964 deg
};
P[69]{
   GP1:
    UF : 6, UT : 8,
    J1=    1.599 deg, J2=    5.652 deg, J3=  -46.498 deg,
    J4=   54.622 deg, J5=   21.834 deg, J6=  -46.273 deg
};
P[70]{
   GP1:
    UF : 6, UT : 8,
    J1=    1.714 deg, J2=    5.523 deg, J3=  -46.410 deg,
    J4=   54.822 deg, J5=   21.848 deg, J6=  -46.433 deg
};
P[71]{
   GP1:
    UF : 6, UT : 8,
    J1=    1.978 deg, J2=    5.812 deg, J3=  -46.558 deg,
    J4=   54.932 deg, J5=   21.660 deg, J6=  -46.497 deg
};
P[72]{
   GP1:
    UF : 6, UT : 8,
    J1=    2.335 deg, J2=    6.510 deg, J3=  -46.964 deg,
    J4=   54.997 deg, J5=   21.304 deg, J6=  -46.369 deg
};
P[73]{
   GP1:
    UF : 6, UT : 8,
    J1=    2.748 deg, J2=    7.610 deg, J3=  -47.662 deg,
    J4=   54.984 deg, J5=   20.815 deg, J6=  -46.103 deg
};
P[74]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.214 deg, J2=    9.045 deg, J3=  -48.595 deg,
    J4=   54.946 deg, J5=   20.229 deg, J6=  -45.768 deg
};
P[75]{
   GP1:
    UF : 6, UT : 8,
    J1=    3.747 deg, J2=   10.757 deg, J3=  -49.687 deg,
    J4=   54.895 deg, J5=   19.602 deg, J6=  -45.376 deg
};
P[76]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.335 deg, J2=   12.662 deg, J3=  -50.888 deg,
    J4=   54.837 deg, J5=   18.956 deg, J6=  -44.902 deg
};
P[77]{
   GP1:
    UF : 6, UT : 8,
    J1=    4.961 deg, J2=   14.668 deg, J3=  -52.095 deg,
    J4=   54.728 deg, J5=   18.304 deg, J6=  -44.374 deg
};
P[78]{
   GP1:
    UF : 6, UT : 8,
    J1=    5.584 deg, J2=   16.633 deg, J3=  -53.182 deg,
    J4=   54.555 deg, J5=   17.643 deg, J6=  -43.833 deg
};
P[79]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.160 deg, J2=   18.488 deg, J3=  -54.128 deg,
    J4=   54.355 deg, J5=   16.982 deg, J6=  -43.244 deg
};
P[80]{
   GP1:
    UF : 6, UT : 8,
    J1=    6.665 deg, J2=   20.231 deg, J3=  -54.993 deg,
    J4=   54.106 deg, J5=   16.300 deg, J6=  -42.666 deg
};
P[81]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.081 deg, J2=   21.763 deg, J3=  -55.766 deg,
    J4=   53.860 deg, J5=   15.618 deg, J6=  -42.132 deg
};
P[82]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.386 deg, J2=   22.836 deg, J3=  -56.173 deg,
    J4=   53.628 deg, J5=   15.011 deg, J6=  -41.667 deg
};
P[83]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.629 deg, J2=   23.472 deg, J3=  -56.269 deg,
    J4=   53.478 deg, J5=   14.577 deg, J6=  -41.335 deg
};
P[84]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.806 deg, J2=   23.572 deg, J3=  -56.189 deg,
    J4=   53.413 deg, J5=   14.318 deg, J6=  -41.185 deg
};
P[85]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.702 deg, J2=   24.434 deg, J3=  -57.152 deg,
    J4=   53.409 deg, J5=   14.241 deg, J6=  -41.186 deg
};
P[86]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.702 deg, J2=   24.434 deg, J3=  -57.152 deg,
    J4=   53.409 deg, J5=   14.241 deg, J6=  -41.186 deg
};
P[87]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -129.068  mm,    Z =   29.996  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[88]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -129.068  mm,    Z =   29.996  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[89]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -129.068  mm,    Z =   29.996  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[90]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.702 deg, J2=   24.434 deg, J3=  -57.152 deg,
    J4=   53.409 deg, J5=   14.241 deg, J6=  -41.186 deg
};
P[91]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.702 deg, J2=   24.434 deg, J3=  -57.152 deg,
    J4=   53.409 deg, J5=   14.241 deg, J6=  -41.186 deg
};
P[92]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.708 deg, J2=   24.330 deg, J3=  -57.069 deg,
    J4=   53.466 deg, J5=   14.183 deg, J6=  -41.267 deg
};
P[93]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.717 deg, J2=   24.120 deg, J3=  -56.890 deg,
    J4=   53.591 deg, J5=   14.076 deg, J6=  -41.447 deg
};
P[94]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.724 deg, J2=   23.824 deg, J3=  -56.635 deg,
    J4=   53.795 deg, J5=   13.935 deg, J6=  -41.734 deg
};
P[95]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.732 deg, J2=   23.458 deg, J3=  -56.316 deg,
    J4=   54.090 deg, J5=   13.772 deg, J6=  -42.139 deg
};
P[96]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.745 deg, J2=   23.035 deg, J3=  -55.935 deg,
    J4=   54.491 deg, J5=   13.598 deg, J6=  -42.672 deg
};
P[97]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.777 deg, J2=   22.573 deg, J3=  -55.511 deg,
    J4=   55.009 deg, J5=   13.422 deg, J6=  -43.340 deg
};
P[98]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.834 deg, J2=   22.092 deg, J3=  -55.051 deg,
    J4=   55.653 deg, J5=   13.249 deg, J6=  -44.146 deg
};
P[99]{
   GP1:
    UF : 6, UT : 8,
    J1=    7.933 deg, J2=   21.620 deg, J3=  -54.608 deg,
    J4=   56.429 deg, J5=   13.078 deg, J6=  -45.090 deg
};
P[100]{
   GP1:
    UF : 6, UT : 8,
    J1=    8.082 deg, J2=   21.182 deg, J3=  -54.211 deg,
    J4=   57.338 deg, J5=   12.912 deg, J6=  -46.169 deg
};
P[101]{
   GP1:
    UF : 6, UT : 8,
    J1=    8.277 deg, J2=   20.786 deg, J3=  -53.851 deg,
    J4=   58.378 deg, J5=   12.757 deg, J6=  -47.376 deg
};
P[102]{
   GP1:
    UF : 6, UT : 8,
    J1=    8.514 deg, J2=   20.439 deg, J3=  -53.519 deg,
    J4=   59.546 deg, J5=   12.614 deg, J6=  -48.705 deg
};
P[103]{
   GP1:
    UF : 6, UT : 8,
    J1=    8.790 deg, J2=   20.150 deg, J3=  -53.215 deg,
    J4=   60.836 deg, J5=   12.484 deg, J6=  -50.144 deg
};
P[104]{
   GP1:
    UF : 6, UT : 8,
    J1=    9.105 deg, J2=   19.927 deg, J3=  -52.938 deg,
    J4=   62.238 deg, J5=   12.367 deg, J6=  -51.679 deg
};
P[105]{
   GP1:
    UF : 6, UT : 8,
    J1=    9.459 deg, J2=   19.772 deg, J3=  -52.683 deg,
    J4=   63.738 deg, J5=   12.258 deg, J6=  -53.294 deg
};
P[106]{
   GP1:
    UF : 6, UT : 8,
    J1=    9.847 deg, J2=   19.684 deg, J3=  -52.443 deg,
    J4=   65.320 deg, J5=   12.152 deg, J6=  -54.965 deg
};
P[107]{
   GP1:
    UF : 6, UT : 8,
    J1=   10.263 deg, J2=   19.657 deg, J3=  -52.219 deg,
    J4=   66.965 deg, J5=   12.049 deg, J6=  -56.672 deg
};
P[108]{
   GP1:
    UF : 6, UT : 8,
    J1=   10.702 deg, J2=   19.688 deg, J3=  -52.014 deg,
    J4=   68.650 deg, J5=   11.948 deg, J6=  -58.392 deg
};
P[109]{
   GP1:
    UF : 6, UT : 8,
    J1=   11.151 deg, J2=   19.766 deg, J3=  -51.828 deg,
    J4=   70.351 deg, J5=   11.852 deg, J6=  -60.106 deg
};
P[110]{
   GP1:
    UF : 6, UT : 8,
    J1=   11.592 deg, J2=   19.886 deg, J3=  -51.649 deg,
    J4=   72.044 deg, J5=   11.760 deg, J6=  -61.795 deg
};
P[111]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.000 deg, J2=   20.039 deg, J3=  -51.475 deg,
    J4=   73.702 deg, J5=   11.672 deg, J6=  -63.436 deg
};
P[112]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.352 deg, J2=   20.218 deg, J3=  -51.304 deg,
    J4=   75.297 deg, J5=   11.581 deg, J6=  -65.008 deg
};
P[113]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.638 deg, J2=   20.416 deg, J3=  -51.144 deg,
    J4=   76.803 deg, J5=   11.488 deg, J6=  -66.483 deg
};
P[114]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.856 deg, J2=   20.621 deg, J3=  -51.004 deg,
    J4=   78.188 deg, J5=   11.389 deg, J6=  -67.831 deg
};
P[115]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.006 deg, J2=   20.824 deg, J3=  -50.891 deg,
    J4=   79.420 deg, J5=   11.283 deg, J6=  -69.019 deg
};
P[116]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.094 deg, J2=   21.010 deg, J3=  -50.805 deg,
    J4=   80.463 deg, J5=   11.171 deg, J6=  -70.017 deg
};
P[117]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.134 deg, J2=   21.165 deg, J3=  -50.737 deg,
    J4=   81.279 deg, J5=   11.064 deg, J6=  -70.793 deg
};
P[118]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.147 deg, J2=   21.272 deg, J3=  -50.687 deg,
    J4=   81.835 deg, J5=   10.980 deg, J6=  -71.321 deg
};
P[119]{
   GP1:
    UF : 6, UT : 8,
    J1=   13.150 deg, J2=   21.325 deg, J3=  -50.659 deg,
    J4=   82.105 deg, J5=   10.935 deg, J6=  -71.578 deg
};
P[120]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.870 deg, J2=   21.144 deg, J3=  -49.851 deg,
    J4=   82.061 deg, J5=   10.846 deg, J6=  -71.563 deg
};
P[121]{
   GP1:
    UF : 6, UT : 8,
    J1=   12.870 deg, J2=   21.144 deg, J3=  -49.851 deg,
    J4=   82.061 deg, J5=   10.846 deg, J6=  -71.563 deg
};
P[122]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =    5.059  mm,    Y =    0.000  mm,    Z =  106.062  mm,
    W =  156.329 deg,    P =  -39.460 deg,    R =   34.596 deg
};
P[123]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =  111.125  mm,    Y =    0.000  mm,    Z =   -0.004  mm,
    W =  156.329 deg,    P =  -39.460 deg,    R =   34.596 deg
};
P[124]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =  111.125  mm,    Y = -258.135  mm,    Z =   -0.004  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[125]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =    5.059  mm,    Y = -258.135  mm,    Z =  106.062  mm,
    W =  159.464 deg,    P =  -40.967 deg,    R =   29.743 deg
};
P[126]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.887 deg, J2=   19.243 deg, J3=  -50.537 deg,
    J4=   87.404 deg, J5=   15.867 deg, J6=  -70.633 deg
};
P[127]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.889 deg, J2=   19.086 deg, J3=  -50.393 deg,
    J4=   86.343 deg, J5=   15.886 deg, J6=  -69.777 deg
};
P[128]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.887 deg, J2=   18.793 deg, J3=  -50.122 deg,
    J4=   84.142 deg, J5=   15.922 deg, J6=  -68.002 deg
};
P[129]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.879 deg, J2=   18.415 deg, J3=  -49.768 deg,
    J4=   80.867 deg, J5=   15.973 deg, J6=  -65.361 deg
};
P[130]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.861 deg, J2=   18.002 deg, J3=  -49.378 deg,
    J4=   76.601 deg, J5=   16.032 deg, J6=  -61.922 deg
};
P[131]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.831 deg, J2=   17.606 deg, J3=  -48.996 deg,
    J4=   71.430 deg, J5=   16.097 deg, J6=  -57.754 deg
};
P[132]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.788 deg, J2=   17.258 deg, J3=  -48.652 deg,
    J4=   65.443 deg, J5=   16.164 deg, J6=  -52.931 deg
};
P[133]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.735 deg, J2=   16.961 deg, J3=  -48.350 deg,
    J4=   58.734 deg, J5=   16.234 deg, J6=  -47.525 deg
};
P[134]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.313 deg, J2=   16.155 deg, J3=  -47.364 deg,
    J4=   -0.886 deg, J5=   16.751 deg, J6=    0.462 deg
};
P[135]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.066 deg, J2=   17.499 deg, J3=  -48.230 deg,
    J4=  -60.519 deg, J5=   17.102 deg, J6=   48.450 deg
};
P[136]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.049 deg, J2=   17.853 deg, J3=  -48.510 deg,
    J4=  -67.235 deg, J5=   17.123 deg, J6=   53.857 deg
};
P[137]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.044 deg, J2=   18.246 deg, J3=  -48.834 deg,
    J4=  -73.230 deg, J5=   17.132 deg, J6=   58.682 deg
};
P[138]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.050 deg, J2=   18.674 deg, J3=  -49.196 deg,
    J4=  -78.413 deg, J5=   17.129 deg, J6=   62.852 deg
};
P[139]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.063 deg, J2=   19.109 deg, J3=  -49.568 deg,
    J4=  -82.695 deg, J5=   17.115 deg, J6=   66.296 deg
};
P[140]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.077 deg, J2=   19.500 deg, J3=  -49.906 deg,
    J4=  -85.985 deg, J5=   17.097 deg, J6=   68.944 deg
};
P[141]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.267 deg, J5=   17.068 deg, J6=   71.584 deg
};
P[142]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.268 deg, J5=   17.068 deg, J6=   71.585 deg
};
P[143]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.268 deg, J5=   17.068 deg, J6=   71.585 deg
};
P[144]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.268 deg, J5=   17.068 deg, J6=   71.585 deg
};
P[145]{
   GP1:
    UF : 6, UT : 8,
    J1=   -0.107 deg, J2=   19.450 deg, J3=  -50.112 deg,
    J4=  -88.915 deg, J5=   17.336 deg, J6=   71.132 deg
};
P[146]{
   GP1:
    UF : 6, UT : 8,
    J1=   -0.500 deg, J2=   18.449 deg, J3=  -49.728 deg,
    J4=  -88.240 deg, J5=   17.854 deg, J6=   70.272 deg
};
P[147]{
   GP1:
    UF : 6, UT : 8,
    J1=   -1.055 deg, J2=   17.047 deg, J3=  -49.170 deg,
    J4=  -87.267 deg, J5=   18.566 deg, J6=   69.060 deg
};
P[148]{
   GP1:
    UF : 6, UT : 8,
    J1=   -1.739 deg, J2=   15.354 deg, J3=  -48.500 deg,
    J4=  -86.042 deg, J5=   19.428 deg, J6=   67.521 deg
};
P[149]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.523 deg, J2=   13.475 deg, J3=  -47.784 deg,
    J4=  -84.628 deg, J5=   20.399 deg, J6=   65.742 deg
};
P[150]{
   GP1:
    UF : 6, UT : 8,
    J1=   -3.374 deg, J2=   11.507 deg, J3=  -47.062 deg,
    J4=  -83.117 deg, J5=   21.434 deg, J6=   63.865 deg
};
P[151]{
   GP1:
    UF : 6, UT : 8,
    J1=   -4.261 deg, J2=    9.533 deg, J3=  -46.348 deg,
    J4=  -81.601 deg, J5=   22.488 deg, J6=   62.003 deg
};
P[152]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.162 deg, J2=    7.622 deg, J3=  -45.672 deg,
    J4=  -80.189 deg, J5=   23.521 deg, J6=   60.214 deg
};
P[153]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.054 deg, J2=    5.854 deg, J3=  -45.066 deg,
    J4=  -78.899 deg, J5=   24.501 deg, J6=   58.517 deg
};
P[154]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.906 deg, J2=    4.316 deg, J3=  -44.589 deg,
    J4=  -77.743 deg, J5=   25.393 deg, J6=   56.981 deg
};
P[155]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.688 deg, J2=    3.084 deg, J3=  -44.267 deg,
    J4=  -76.720 deg, J5=   26.164 deg, J6=   55.648 deg
};
P[156]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.373 deg, J2=    2.217 deg, J3=  -44.117 deg,
    J4=  -75.853 deg, J5=   26.777 deg, J6=   54.550 deg
};
P[157]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.947 deg, J2=    1.731 deg, J3=  -44.131 deg,
    J4=  -75.171 deg, J5=   27.211 deg, J6=   53.677 deg
};
P[158]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.389 deg, J2=    1.641 deg, J3=  -44.271 deg,
    J4=  -74.631 deg, J5=   27.452 deg, J6=   53.006 deg
};
P[159]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.687 deg, J2=    1.955 deg, J3=  -44.543 deg,
    J4=  -74.194 deg, J5=   27.488 deg, J6=   52.508 deg
};
P[160]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.821 deg, J2=    2.703 deg, J3=  -44.955 deg,
    J4=  -73.775 deg, J5=   27.305 deg, J6=   52.148 deg
};
P[161]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.756 deg, J2=    3.927 deg, J3=  -45.576 deg,
    J4=  -73.354 deg, J5=   26.883 deg, J6=   51.884 deg
};
P[162]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.481 deg, J2=    5.620 deg, J3=  -46.397 deg,
    J4=  -72.893 deg, J5=   26.229 deg, J6=   51.689 deg
};
P[163]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.036 deg, J2=    7.707 deg, J3=  -47.385 deg,
    J4=  -72.394 deg, J5=   25.379 deg, J6=   51.528 deg
};
P[164]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.510 deg, J2=   10.019 deg, J3=  -48.423 deg,
    J4=  -71.862 deg, J5=   24.406 deg, J6=   51.399 deg
};
P[165]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.972 deg, J2=   12.397 deg, J3=  -49.428 deg,
    J4=  -71.303 deg, J5=   23.375 deg, J6=   51.283 deg
};
P[166]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.455 deg, J2=   14.744 deg, J3=  -50.446 deg,
    J4=  -70.736 deg, J5=   22.324 deg, J6=   51.175 deg
};
P[167]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.973 deg, J2=   17.029 deg, J3=  -51.487 deg,
    J4=  -70.147 deg, J5=   21.284 deg, J6=   51.064 deg
};
P[168]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.550 deg, J2=   19.213 deg, J3=  -52.546 deg,
    J4=  -69.558 deg, J5=   20.293 deg, J6=   50.953 deg
};
P[169]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.191 deg, J2=   21.174 deg, J3=  -53.514 deg,
    J4=  -69.008 deg, J5=   19.404 deg, J6=   50.865 deg
};
P[170]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.888 deg, J2=   22.782 deg, J3=  -54.306 deg,
    J4=  -68.571 deg, J5=   18.674 deg, J6=   50.803 deg
};
P[171]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.681 deg, J2=   23.918 deg, J3=  -54.939 deg,
    J4=  -68.300 deg, J5=   18.154 deg, J6=   50.774 deg
};
P[172]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.586 deg, J2=   24.578 deg, J3=  -55.408 deg,
    J4=  -68.190 deg, J5=   17.892 deg, J6=   50.760 deg
};
P[173]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.242 deg, J2=   25.792 deg, J3=  -56.483 deg,
    J4=  -68.103 deg, J5=   17.645 deg, J6=   50.663 deg
};
P[174]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.242 deg, J2=   25.792 deg, J3=  -56.483 deg,
    J4=  -68.103 deg, J5=   17.645 deg, J6=   50.663 deg
};
P[175]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -740.883  mm,    Z =   28.280  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[176]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -740.883  mm,    Z =   28.280  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[177]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   81.125  mm,    Y = -740.883  mm,    Z =   28.280  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[178]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.242 deg, J2=   25.792 deg, J3=  -56.483 deg,
    J4=  -68.103 deg, J5=   17.645 deg, J6=   50.663 deg
};
P[179]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.242 deg, J2=   25.792 deg, J3=  -56.483 deg,
    J4=  -68.103 deg, J5=   17.645 deg, J6=   50.663 deg
};
P[180]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.188 deg, J2=   25.258 deg, J3=  -56.061 deg,
    J4=  -67.910 deg, J5=   17.773 deg, J6=   50.406 deg
};
P[181]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.165 deg, J2=   24.293 deg, J3=  -55.394 deg,
    J4=  -67.573 deg, J5=   18.045 deg, J6=   49.937 deg
};
P[182]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.300 deg, J2=   23.011 deg, J3=  -54.667 deg,
    J4=  -67.178 deg, J5=   18.497 deg, J6=   49.343 deg
};
P[183]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.706 deg, J2=   21.523 deg, J3=  -54.050 deg,
    J4=  -66.817 deg, J5=   19.167 deg, J6=   48.698 deg
};
P[184]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.344 deg, J2=   19.813 deg, J3=  -53.437 deg,
    J4=  -66.536 deg, J5=   20.056 deg, J6=   48.043 deg
};
P[185]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.138 deg, J2=   17.915 deg, J3=  -52.802 deg,
    J4=  -66.296 deg, J5=   21.097 deg, J6=   47.371 deg
};
P[186]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.000 deg, J2=   15.926 deg, J3=  -52.107 deg,
    J4=  -66.042 deg, J5=   22.185 deg, J6=   46.673 deg
};
P[187]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.828 deg, J2=   13.940 deg, J3=  -51.296 deg,
    J4=  -65.751 deg, J5=   23.235 deg, J6=   45.967 deg
};
P[188]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.542 deg, J2=   12.039 deg, J3=  -50.356 deg,
    J4=  -65.429 deg, J5=   24.188 deg, J6=   45.282 deg
};
P[189]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.092 deg, J2=   10.347 deg, J3=  -49.379 deg,
    J4=  -65.084 deg, J5=   24.990 deg, J6=   44.647 deg
};
P[190]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.461 deg, J2=    8.943 deg, J3=  -48.468 deg,
    J4=  -64.733 deg, J5=   25.599 deg, J6=   44.086 deg
};
P[191]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.641 deg, J2=    7.909 deg, J3=  -47.715 deg,
    J4=  -64.401 deg, J5=   25.992 deg, J6=   43.633 deg
};
P[192]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.636 deg, J2=    7.297 deg, J3=  -47.172 deg,
    J4=  -64.124 deg, J5=   26.166 deg, J6=   43.317 deg
};
P[193]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.510 deg, J2=    7.147 deg, J3=  -46.936 deg,
    J4=  -63.918 deg, J5=   26.117 deg, J6=   43.151 deg
};
P[194]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.293 deg, J2=    7.482 deg, J3=  -47.088 deg,
    J4=  -63.810 deg, J5=   25.869 deg, J6=   43.147 deg
};
P[195]{
   GP1:
    UF : 6, UT : 8,
    J1=  -10.039 deg, J2=    8.255 deg, J3=  -47.594 deg,
    J4=  -63.833 deg, J5=   25.475 deg, J6=   43.325 deg
};
P[196]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.773 deg, J2=    9.341 deg, J3=  -48.297 deg,
    J4=  -64.028 deg, J5=   25.000 deg, J6=   43.701 deg
};
P[197]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.489 deg, J2=   10.661 deg, J3=  -49.131 deg,
    J4=  -64.419 deg, J5=   24.479 deg, J6=   44.279 deg
};
P[198]{
   GP1:
    UF : 6, UT : 8,
    J1=   -9.136 deg, J2=   12.142 deg, J3=  -50.024 deg,
    J4=  -64.963 deg, J5=   23.867 deg, J6=   45.024 deg
};
P[199]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.663 deg, J2=   13.782 deg, J3=  -50.926 deg,
    J4=  -65.570 deg, J5=   23.124 deg, J6=   45.866 deg
};
P[200]{
   GP1:
    UF : 6, UT : 8,
    J1=   -8.083 deg, J2=   15.550 deg, J3=  -51.747 deg,
    J4=  -66.132 deg, J5=   22.311 deg, J6=   46.724 deg
};
P[201]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.419 deg, J2=   17.377 deg, J3=  -52.440 deg,
    J4=  -66.609 deg, J5=   21.399 deg, J6=   47.554 deg
};
P[202]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.771 deg, J2=   19.205 deg, J3=  -53.062 deg,
    J4=  -67.015 deg, J5=   20.471 deg, J6=   48.340 deg
};
P[203]{
   GP1:
    UF : 6, UT : 8,
    J1=   -6.209 deg, J2=   20.984 deg, J3=  -53.707 deg,
    J4=  -67.372 deg, J5=   19.615 deg, J6=   49.069 deg
};
P[204]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.765 deg, J2=   22.641 deg, J3=  -54.417 deg,
    J4=  -67.682 deg, J5=   18.863 deg, J6=   49.711 deg
};
P[205]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.457 deg, J2=   24.091 deg, J3=  -55.187 deg,
    J4=  -67.949 deg, J5=   18.251 deg, J6=   50.244 deg
};
P[206]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.333 deg, J2=   25.110 deg, J3=  -55.819 deg,
    J4=  -68.178 deg, J5=   17.863 deg, J6=   50.650 deg
};
P[207]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.365 deg, J2=   25.433 deg, J3=  -55.943 deg,
    J4=  -68.322 deg, J5=   17.744 deg, J6=   50.879 deg
};
P[208]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.227 deg, J2=   25.923 deg, J3=  -56.419 deg,
    J4=  -68.310 deg, J5=   17.629 deg, J6=   50.867 deg
};
P[209]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.227 deg, J2=   25.923 deg, J3=  -56.419 deg,
    J4=  -68.310 deg, J5=   17.629 deg, J6=   50.867 deg
};
P[210]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -740.883  mm,    Z =   29.996  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[211]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -740.883  mm,    Z =   29.996  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[212]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =   82.841  mm,    Y = -740.883  mm,    Z =   29.996  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[213]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.227 deg, J2=   25.923 deg, J3=  -56.419 deg,
    J4=  -68.310 deg, J5=   17.629 deg, J6=   50.867 deg
};
P[214]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.227 deg, J2=   25.923 deg, J3=  -56.419 deg,
    J4=  -68.310 deg, J5=   17.629 deg, J6=   50.867 deg
};
P[215]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.203 deg, J2=   25.717 deg, J3=  -56.283 deg,
    J4=  -68.444 deg, J5=   17.680 deg, J6=   50.990 deg
};
P[216]{
   GP1:
    UF : 6, UT : 8,
    J1=   -5.126 deg, J2=   25.328 deg, J3=  -56.005 deg,
    J4=  -68.701 deg, J5=   17.776 deg, J6=   51.225 deg
};
P[217]{
   GP1:
    UF : 6, UT : 8,
    J1=   -4.977 deg, J2=   24.801 deg, J3=  -55.634 deg,
    J4=  -69.064 deg, J5=   17.892 deg, J6=   51.554 deg
};
P[218]{
   GP1:
    UF : 6, UT : 8,
    J1=   -4.705 deg, J2=   24.173 deg, J3=  -55.214 deg,
    J4=  -69.532 deg, J5=   17.991 deg, J6=   51.966 deg
};
P[219]{
   GP1:
    UF : 6, UT : 8,
    J1=   -4.318 deg, J2=   23.478 deg, J3=  -54.767 deg,
    J4=  -70.104 deg, J5=   18.072 deg, J6=   52.450 deg
};
P[220]{
   GP1:
    UF : 6, UT : 8,
    J1=   -3.865 deg, J2=   22.732 deg, J3=  -54.250 deg,
    J4=  -70.760 deg, J5=   18.160 deg, J6=   52.996 deg
};
P[221]{
   GP1:
    UF : 6, UT : 8,
    J1=   -3.390 deg, J2=   21.979 deg, J3=  -53.658 deg,
    J4=  -71.479 deg, J5=   18.261 deg, J6=   53.598 deg
};
P[222]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.967 deg, J2=   21.237 deg, J3=  -52.988 deg,
    J4=  -72.255 deg, J5=   18.380 deg, J6=   54.261 deg
};
P[223]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.638 deg, J2=   20.520 deg, J3=  -52.281 deg,
    J4=  -73.097 deg, J5=   18.504 deg, J6=   54.997 deg
};
P[224]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.436 deg, J2=   19.828 deg, J3=  -51.600 deg,
    J4=  -74.004 deg, J5=   18.638 deg, J6=   55.803 deg
};
P[225]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.366 deg, J2=   19.195 deg, J3=  -51.025 deg,
    J4=  -74.977 deg, J5=   18.791 deg, J6=   56.677 deg
};
P[226]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.398 deg, J2=   18.651 deg, J3=  -50.595 deg,
    J4=  -76.015 deg, J5=   18.967 deg, J6=   57.617 deg
};
P[227]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.495 deg, J2=   18.197 deg, J3=  -50.256 deg,
    J4=  -77.116 deg, J5=   19.150 deg, J6=   58.626 deg
};
P[228]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.620 deg, J2=   17.824 deg, J3=  -49.971 deg,
    J4=  -78.258 deg, J5=   19.308 deg, J6=   59.692 deg
};
P[229]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.741 deg, J2=   17.550 deg, J3=  -49.734 deg,
    J4=  -79.411 deg, J5=   19.415 deg, J6=   60.789 deg
};
P[230]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.821 deg, J2=   17.371 deg, J3=  -49.546 deg,
    J4=  -80.557 deg, J5=   19.473 deg, J6=   61.897 deg
};
P[231]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.830 deg, J2=   17.292 deg, J3=  -49.439 deg,
    J4=  -81.696 deg, J5=   19.491 deg, J6=   63.007 deg
};
P[232]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.754 deg, J2=   17.331 deg, J3=  -49.455 deg,
    J4=  -82.833 deg, J5=   19.466 deg, J6=   64.125 deg
};
P[233]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.597 deg, J2=   17.501 deg, J3=  -49.593 deg,
    J4=  -83.941 deg, J5=   19.376 deg, J6=   65.234 deg
};
P[234]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.379 deg, J2=   17.768 deg, J3=  -49.801 deg,
    J4=  -84.982 deg, J5=   19.208 deg, J6=   66.311 deg
};
P[235]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.116 deg, J2=   18.090 deg, J3=  -50.024 deg,
    J4=  -85.914 deg, J5=   18.970 deg, J6=   67.319 deg
};
P[236]{
   GP1:
    UF : 6, UT : 8,
    J1=   -1.813 deg, J2=   18.445 deg, J3=  -50.239 deg,
    J4=  -86.724 deg, J5=   18.684 deg, J6=   68.242 deg
};
P[237]{
   GP1:
    UF : 6, UT : 8,
    J1=   -1.466 deg, J2=   18.816 deg, J3=  -50.416 deg,
    J4=  -87.417 deg, J5=   18.371 deg, J6=   69.074 deg
};
P[238]{
   GP1:
    UF : 6, UT : 8,
    J1=   -1.084 deg, J2=   19.163 deg, J3=  -50.509 deg,
    J4=  -88.000 deg, J5=   18.045 deg, J6=   69.814 deg
};
P[239]{
   GP1:
    UF : 6, UT : 8,
    J1=   -0.695 deg, J2=   19.458 deg, J3=  -50.496 deg,
    J4=  -88.473 deg, J5=   17.718 deg, J6=   70.452 deg
};
P[240]{
   GP1:
    UF : 6, UT : 8,
    J1=   -0.337 deg, J2=   19.692 deg, J3=  -50.422 deg,
    J4=  -88.843 deg, J5=   17.419 deg, J6=   70.979 deg
};
P[241]{
   GP1:
    UF : 6, UT : 8,
    J1=   -0.059 deg, J2=   19.865 deg, J3=  -50.346 deg,
    J4=  -89.121 deg, J5=   17.190 deg, J6=   71.375 deg
};
P[242]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.961 deg, J3=  -50.308 deg,
    J4=  -89.280 deg, J5=   17.070 deg, J6=   71.595 deg
};
P[243]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.268 deg, J5=   17.068 deg, J6=   71.585 deg
};
P[244]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.092 deg, J2=   19.958 deg, J3=  -50.300 deg,
    J4=  -89.268 deg, J5=   17.068 deg, J6=   71.585 deg
};
P[245]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =    5.059  mm,    Y = -611.815  mm,    Z =  106.062  mm,
    W = -156.329 deg,    P =  -39.460 deg,    R =  -34.596 deg
};
P[246]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =  111.125  mm,    Y = -611.815  mm,    Z =   -0.004  mm,
    W = -156.329 deg,    P =  -39.460 deg,    R =  -34.596 deg
};
P[247]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =  111.125  mm,    Y = -869.950  mm,    Z =   -0.004  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[248]{
   GP1:
    UF : 6, UT : 8,        CONFIG : 'F U T, 0, 0, 0',
    X =    5.059  mm,    Y = -869.950  mm,    Z =  106.062  mm,
    W = -153.435 deg,    P =  -37.761 deg,    R =  -39.232 deg
};
P[249]{
   GP1:
    UF : 6, UT : 8,
    J1=  -11.653 deg, J2=   22.485 deg, J3=  -49.281 deg,
    J4=  -86.312 deg, J5=   12.160 deg, J6=   74.758 deg
};
P[250]{
   GP1:
    UF : 6, UT : 8,
    J1=  -11.276 deg, J2=   16.253 deg, J3=  -45.623 deg,
    J4=  -72.234 deg, J5=    3.339 deg, J6=   62.596 deg
};
P[251]{
   GP1:
    UF : 6, UT : 8,
    J1=   -7.195 deg, J2=    2.801 deg, J3=  -23.795 deg,
    J4=  -42.924 deg, J5=  -15.764 deg, J6=   37.401 deg
};
P[252]{
   GP1:
    UF : 6, UT : 8,
    J1=   -2.699 deg, J2=  -10.304 deg, J3=    2.662 deg,
    J4=  -13.731 deg, J5=  -35.373 deg, J6=   12.041 deg
};
P[253]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.499 deg, J3=   16.499 deg,
    J4=    0.000 deg, J5=  -44.997 deg, J6=    0.000 deg
};
P[254]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[255]{
   GP1:
    UF : 6, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
P[256]{
   GP1:
    UF : 9, UT : 8,
    J1=    0.000 deg, J2=  -16.500 deg, J3=   16.500 deg,
    J4=    0.000 deg, J5=  -45.000 deg, J6=    0.000 deg
};
/END
